### ISSUE TITLE
Scrollable Screen when keyboard is present

### ISSUE THREAD

**Issue by iamjamieseymour** [evolutionise/Pocket-WBS#18]
Client request for a scrollable screen when the keyboard is present in edit element and activity screens. Remove keyboard popup on the start of these activities if possible.

**Comment by adrianmwy** [comment]
*Removed keyboard popup on the start of both activities
*Edit Element screen : Attempted to implement big parent scrollview but complications arose with listView's scrolling... checked multiple forums .. advised not to have such complex UI.

*Edit Activity screen : Scroll implemented
