### ISSUE TITLE
Newline character not supported in Elements

### ISSUE THREAD

**Issue by evolutionise** [evolutionise/Pocket-WBS#4]
Need to add a catch for this perhaps including a warning about using the return character.  Also check that this is actually what is causing the crash.

**Comment by iamjamieseymour** [comment]
In response to Farah's comment, I've sorted out that one now, we had code that would throw an exception if the root elements name was changed (says the root element has to be named after the project). Added a project tree method that would allow project renaming.

**Comment by iamjamieseymour** [comment]
Tested what Alix has mentioned, works without creating crashes, did you fix this @evolutionise? In the element overview it displays as a straight line which is good.
